/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GetRouteImport } from './routes/get'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WlanRouteImport } from './routes/wlan'
import { Route as ApiLanRouteImport } from './routes/api/lan'
import { Route as ApiNativeRouteImport } from './routes/api/native'
import { Route as ApiPaypalIpnRouteImport } from './routes/api/paypal-ipn'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as CConversationIdRouteImport } from './routes/c.$conversationId'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GetRoute = GetRouteImport.update({
  id: '/get',
  path: '/get',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WlanRoute = WlanRouteImport.update({
  id: '/wlan',
  path: '/wlan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLanRoute = ApiLanRouteImport.update({
  id: '/api/lan',
  path: '/api/lan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeRoute = ApiNativeRouteImport.update({
  id: '/api/native',
  path: '/api/native',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalIpnRoute = ApiPaypalIpnRouteImport.update({
  id: '/api/paypal-ipn',
  path: '/api/paypal-ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const CConversationIdRoute = CConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/get': typeof GetRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/wlan': typeof WlanRoute
  '/api/lan': typeof ApiLanRoute
  '/api/native': typeof ApiNativeRoute
  '/api/paypal-ipn': typeof ApiPaypalIpnRoute
  '/api/rtc': typeof ApiRtcRoute
  '/c/$conversationId': typeof CConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/get': typeof GetRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/wlan': typeof WlanRoute
  '/api/lan': typeof ApiLanRoute
  '/api/native': typeof ApiNativeRoute
  '/api/paypal-ipn': typeof ApiPaypalIpnRoute
  '/api/rtc': typeof ApiRtcRoute
  '/c/$conversationId': typeof CConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/get': typeof GetRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/wlan': typeof WlanRoute
  '/api/lan': typeof ApiLanRoute
  '/api/native': typeof ApiNativeRoute
  '/api/paypal-ipn': typeof ApiPaypalIpnRoute
  '/api/rtc': typeof ApiRtcRoute
  '/c/$conversationId': typeof CConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/get'
    | '/login'
    | '/messages'
    | '/online'
    | '/profile'
    | '/settings'
    | '/wallet'
    | '/wlan'
    | '/api/lan'
    | '/api/native'
    | '/api/paypal-ipn'
    | '/api/rtc'
    | '/c/$conversationId'
    | '/u/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/get'
    | '/login'
    | '/messages'
    | '/online'
    | '/profile'
    | '/settings'
    | '/wallet'
    | '/wlan'
    | '/api/lan'
    | '/api/native'
    | '/api/paypal-ipn'
    | '/api/rtc'
    | '/c/$conversationId'
    | '/u/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/get'
    | '/login'
    | '/messages'
    | '/online'
    | '/profile'
    | '/settings'
    | '/wallet'
    | '/wlan'
    | '/api/lan'
    | '/api/native'
    | '/api/paypal-ipn'
    | '/api/rtc'
    | '/c/$conversationId'
    | '/u/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  GetRoute: typeof GetRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OnlineRoute: typeof OnlineRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRoute
  WlanRoute: typeof WlanRoute
  ApiLanRoute: typeof ApiLanRoute
  ApiNativeRoute: typeof ApiNativeRoute
  ApiPaypalIpnRoute: typeof ApiPaypalIpnRoute
  ApiRtcRoute: typeof ApiRtcRoute
  CConversationIdRoute: typeof CConversationIdRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get': {
      id: '/get'
      path: '/get'
      fullPath: '/get'
      preLoaderRoute: typeof GetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wlan': {
      id: '/wlan'
      path: '/wlan'
      fullPath: '/wlan'
      preLoaderRoute: typeof WlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lan': {
      id: '/api/lan'
      path: '/api/lan'
      fullPath: '/api/lan'
      preLoaderRoute: typeof ApiLanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native': {
      id: '/api/native'
      path: '/api/native'
      fullPath: '/api/native'
      preLoaderRoute: typeof ApiNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal-ipn': {
      id: '/api/paypal-ipn'
      path: '/api/paypal-ipn'
      fullPath: '/api/paypal-ipn'
      preLoaderRoute: typeof ApiPaypalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$conversationId': {
      id: '/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof CConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  GetRoute: GetRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OnlineRoute: OnlineRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
  WlanRoute: WlanRoute,
  ApiLanRoute: ApiLanRoute,
  ApiNativeRoute: ApiNativeRoute,
  ApiPaypalIpnRoute: ApiPaypalIpnRoute,
  ApiRtcRoute: ApiRtcRoute,
  CConversationIdRoute: CConversationIdRoute,
  UUserIdRoute: UUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
