plugins {
    id "com.android.application"
}

android {
    namespace "app.offchat"
    compileSdk 34
    defaultConfig {
        applicationId "app.offchat"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        release {
            storeFile file("offchat.keystore")
            storePassword "offchat1"
            keyAlias "offchat"
            keyPassword "offchat1"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.webkit:webkit:1.11.0"
}
